repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        pass_filenames: true
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        pass_filenames: true
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        pass_filenames: false
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        pass_filenames: true
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true